# Generated by Django 3.2.10 on 2021-12-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lightmanager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pwmchannel",
            old_name="duty_cycle",
            new_name="milli_percent",
        ),
    ]
